name: live4tsdk
description: A live4t SDK to connect api
version: 0.10.1
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dartz: ^0.10.0-nullsafety.1
  dio: ^4.0.0-prev1
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: null
  freezed: ^0.14.1
  pedantic: ^1.9.0
  json_serializable: ^4.0.1
