name: live4tsdk
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  dartz: ^0.9.2
  dio: ^3.0.10
  freezed_annotation: null

dev_dependencies:
  build_runner: null
  freezed: null
  pedantic: ^1.9.0
  test: ^1.14.4
